export const projects = [
  {
    title: 'Personal Portfolio',
    description: "Using Next.js, JavaScript to build my first personal portfolio.",
      image: '/images/6.png',
      tags: ['Next.js', 'JavaScript'],
    source: 'https://github.com/Canepro/portfolio_website-main',
    visit: 'https://codepen.io/canepro/pen/vYemNmm',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Worked with Heritage Bank as an IT Regional Support Officer.', },
  { year: 2019, text: 'Worked with Tek-Experts as a Technical Support Engineer (Stage II).', },
  { year: 2019, text: 'Got my Managing Microsoft 365 Identity & Services (MS 100)', },
  { year: 2020, text: 'Became a TECHNICAL LEAD at Tek-Experts.', },
  { year: 2020, text: 'Joined Crossover for Work as an L1 Technical Support Engineer.', },
  { year: 2021, text: 'Started my DevOps journey', },
  { year: 2022, text: 'Started my Front-End Development journey', },
  { year: 2022, text: 'Also Started working with a tech start-up, Rocket.Chat as A Technical Support Analyst', },
  { year: 2023, text: 'Still working with Rocket.Chat, while improving my DevOps and Cloud skills', },
];